export const VIDEO_GRAB_START = "VIDEO_GRAB_START"
export const VIDEO_GRAB_SUCCESS = "VIDEO_GRAB_SUCCESS"
export const GRAB_QUERY = "GRAB_QUERY"
export const CLEAR_VIDEO = "CLEAR_VIDEO"
export const SET_SHOW = "SET_SHOW"
export const SET_UPDATE = "SET_UPDATE"
export const SET_DATA_MODAL = "SET_DATA_MODAL"
export const BOOK_GRAB = "BOOK_GRAB"